### ISSUE TITLE
Suggestion: Update to 1.17.1

### ISSUE THREAD

**Issue by Minionguyjpro** [NicosaurusRex99/LagFix#7]
Update the mod to 1.17.1
And also, now Forge 1.17.1 is released.
I suggest this because older Minecraft versions are more outdated every year and may we want also be able to play with good performance in newer versions.

**Comment by NicosaurusRex99** [comment]
Noted

**Comment by Minionguyjpro** [comment]
You mean its planned?

**Comment by NicosaurusRex99** [comment]
I mean I'd like to. But 1 I need the original devs permission. 2. Forge isn't on a recommended build yet. 3. I'm busy with divinerpg
